//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class exceptionlog
{
    public int id { get; set; }
    public System.DateTime timestamp { get; set; }
    public string level { get; set; }
    public string logger { get; set; }
    public string message { get; set; }
    public Nullable<int> userid { get; set; }
    public string exception { get; set; }
    public string stacktrace { get; set; }
}

public partial class sysdiagrams
{
    public string name { get; set; }
    public int principal_id { get; set; }
    public int diagram_id { get; set; }
    public Nullable<int> version { get; set; }
    public byte[] definition { get; set; }
}

public partial class TBLKULLANICILAR
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public TBLKULLANICILAR()
    {
        this.TBLPROJE = new HashSet<TBLPROJE>();
    }

    public int OGRID { get; set; }
    public string OGRAD { get; set; }
    public string OGRSOYAD { get; set; }
    public int OGRNO { get; set; }
    public string BOLUM { get; set; }
    public string DONEM { get; set; }
    public string SIFRE { get; set; }
    public string EPOSTA { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<TBLPROJE> TBLPROJE { get; set; }
}

public partial class TBLPROJE
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public TBLPROJE()
    {
        this.TBLRAPOR = new HashSet<TBLRAPOR>();
    }

    public int PROJEID { get; set; }
    public int OGRID { get; set; }
    public string PROJEAD { get; set; }
    public System.DateTime BAŞLAMA { get; set; }
    public System.DateTime BİTİŞ { get; set; }
    public string AÇIKLAMA { get; set; }

    public virtual TBLKULLANICILAR TBLKULLANICILAR { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<TBLRAPOR> TBLRAPOR { get; set; }
}

public partial class TBLRAPOR
{
    public int RAPORID { get; set; }
    public int OGRID { get; set; }
    public System.DateTime YUKLENENTARIH { get; set; }
    public string RAPORAD { get; set; }
    public Nullable<int> HAFTA { get; set; }
    public int PROJEID { get; set; }
    public string DOSYA { get; set; }

    public virtual TBLPROJE TBLPROJE { get; set; }
}
