//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class DBProjeTakipEntities1 : DbContext
{
    public DBProjeTakipEntities1()
        : base("name=DBProjeTakipEntities1")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    public virtual DbSet<TBLKULLANICILAR> TBLKULLANICILAR { get; set; }
    public virtual DbSet<TBLPROJE> TBLPROJE { get; set; }
    public virtual DbSet<TBLRAPOR> TBLRAPOR { get; set; }
    public virtual DbSet<exceptionlog> exceptionlog { get; set; }
}
